spring:
  application:
    name: homepage-zuul
server:
  port: 9000
eureka:
  client:
    #是否从Eureka server中获取注册信息，默认是true
    fetch-registry: true
    #是否将自己注册到Eureka server，默认是true，此处是客户的，需要注册
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka