spring:
  application:
    name: homepage-eureka
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    #是否从Eureka server中获取注册信息，默认是true
    fetch-registry: false
    #是否将自己注册到Eureka server，默认是true，此处是单点server，不需要注册
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka